version: '3'
services:
  rabbit:
    build: .
    image: custom-rabbit
    container_name: assembleia-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rede
  database:
    image: postgres:12-alpine
    container_name: assembleia-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: assembleia
    networks:
      - rede
networks:
    rede:
        driver: bridge