paths:
  /pauta:
    post:
      operationId: criarPauta
      summary: 'Cria uma nova pauta'
      responses:
        '200':
          description: 'Resposta que será dada caso os parâmetros tenham sido passados corretamente.'
          schema:
            x-oad-type: object
            type: object
            properties:
              status:
                x-oad-type: string
                type: string
                enum:
                  - SUCESSO
                  - ERRO
              mensagem:
                x-oad-type: string
                type: string
              data:
                x-oad-type: object
                type: object
                properties:
                  id: {x-oad-type: integer, type: integer, description: 'Id da pauta criada', format: int32}
          x-oad-type: response
        '400':
          description: 'Caso os parâmetros estejam incorretos, a resposta receberá código 400.'
          x-oad-type: response
      parameters:
        -
          name: assunto
          in: body
          description: 'Assunto da pauta'
          required: true
          schema:
            x-oad-type: string
            type: string
          x-oad-type: parameter
    x-oad-type: operation
  /voto:
    post:
      operationId: registrarVoto
      summary: 'Registra um voto na sessão'
      responses:
        '200':
          description: 'Resposta que será dada caso os parâmetros tenham sido passados corretamente.'
          schema:
            x-oad-type: object
            type: object
            properties:
              status:
                x-oad-type: string
                type: string
                enum:
                  - SUCESSO
                  - ERRO
              mensagem:
                x-oad-type: string
                type: string
              data:
                x-oad-type: object
                type: object
                properties:
                  id: {x-oad-type: integer, type: integer, description: 'ID do voto registrado', format: int32}
          x-oad-type: response
        '400':
          description: 'Caso os parâmetros estejam incorretos, a resposta receberá código 400.'
          x-oad-type: response
      parameters:
        -
          name: cpf
          in: body
          description: 'CPF de quem irá votar'
          required: true
          schema:
            x-oad-type: string
            type: string
          x-oad-type: parameter
        -
          name: sessaoVotada
          in: body
          description: 'Sessão em que será realizado o voto'
          required: true
          schema:
            x-oad-type: integer
            type: integer
            format: int32
          x-oad-type: parameter
        -
          name: escolha
          in: body
          description: 'Escolha do voto'
          required: true
          schema:
            x-oad-type: string
            type: string
            enum:
              - SIM
              - NAO
          x-oad-type: parameter
    x-oad-type: operation
  /sessao:
    post:
      operationId: abrirSessao
      responses:
        '200':
          description: 'Resposta que será dada caso os parâmetros tenham sido passados corretamente.'
          schema:
            x-oad-type: object
            type: object
            properties:
              status:
                x-oad-type: string
                type: string
                enum:
                  - SUCESSO
                  - ERRO
              mensagem:
                x-oad-type: string
                type: string
              data:
                x-oad-type: object
                type: object
                properties:
                  id: {x-oad-type: integer, type: integer, description: 'ID da sessão que foi aberta', format: int32}
          x-oad-type: response
        '400':
          description: 'Caso os parâmetros estejam incorretos, a resposta receberá código 400.'
          x-oad-type: response
      parameters:
        -
          name: pauta
          in: body
          required: true
          schema:
            x-oad-type: integer
            type: integer
            title: Pauta
            description: 'ID da pauta sobre a qual será aberta a sessão'
            format: int32
          x-oad-type: parameter
        -
          name: duracaoSessao
          in: body
          description: 'Duração(em segundos) que a sessão ficará em aberto. Não pode ser menor que 1.'
          required: false
          schema:
            x-oad-type: integer
            type: integer
            format: int32
          x-oad-type: parameter
    x-oad-type: operation
  /sessao/resultado:
    get:
      operationId: buscarResultadoSessao
      responses:
        '200':
          description: 'Resposta que será dada caso os parâmetros tenham sido passados corretamente.'
          schema:
            x-oad-type: object
            type: object
            properties:
              status:
                x-oad-type: string
                type: string
                enum:
                  - SUCESSO
                  - ERRO
              mensagem:
                x-oad-type: string
                type: string
              data:
                x-oad-type: object
                type: object
                properties:
                  totalVotos: {x-oad-type: integer, type: integer, description: 'Total de votos que foram registrados na sessão.', format: int32}
                  situacao: {x-oad-type: string, type: string, description: 'Situação da sessão.', enum: [APROVADA, REPROVADA, EMPATE]}
          x-oad-type: response
        '400':
          description: 'Caso os parâmetros estejam incorretos, a resposta receberá código 400.'
          x-oad-type: response
      parameters:
        -
          name: id
          in: path
          description: 'ID da sessão para buscar o resultado.'
          required: true
          type: integer
          format: int32
          x-oad-type: parameter
    x-oad-type: operation
info:
  title: Assembleia
  version: 1.0.0
  description: 'API com a finalidade de simular o funcionamento de uma assembleia.'
  contact:
    name: 'Guilherme Lacerda'
    email: gui.lls@hotmail.com
host: '127.0.0.1:8080'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'
